### ISSUE TITLE
show required configuration parameters an app query

### ISSUE THREAD

**Issue by soichih** [brain-life/cli#10]
Brad suggests we could display required config parameters when a user query for an App. I think we could display a "usage" for each App that user can use as a template for the real config object to pass for --config.

**Comment by stevengeeky** [comment]
PR #15 does this and displays it in the following format for bl app query:

```
Id: 5ab145a5029f78002be2c45a
Name: mrtrix3 act
Service: brain-life/app-mrtrix3-act
Type: (dwi: neuro/dwi, anat: neuro/anat/t1w) -> (tracking: neuro/track, tensor: neuro/tensor)
Description: perform Anatomically Constrained Tractography (ACT) on single or multi-shell data.
Config:
    imaxs: (type: string) (default: 2)
    curvs: (type: string) (default: 5 10 20 40 80)
    num_fibers: (type: string) (default: 25000)
    min_length: (type: string) (default: 10)
    max_length: (type: string) (default: 200)
    tensor_fit: (type: string) (default: ' ')
    ens_lmax: (type: boolean)
    norm: (type: boolean)
    do_prb2: (type: boolean)
    do_prb1: (type: boolean)
    do_detr: (type: boolean)
    do_dtdt: (type: boolean)
    do_dtpb: (type: boolean)
```
